import React, { useState, useEffect } from 'react';
import { 
    Shield, ShieldCheck, Users, Lock, Unlock, Eye, 
    FileText, Trash2, Archive, RefreshCw, Key, 
    Fingerprint, AlertCircle, History, FileDown, Brain, X, Plus, Edit2, MapPin, ArrowLeft
} from 'lucide-react';
import { createPortal } from 'react-dom';
import ProtocolWizard from './ProtocolWizard';
import { TodDesignationPreview, TodAddendumPreview } from './LegalArtifacts';
import { MarketingEngine } from '../../MarketingEngine';
import { supabase } from '../../supabase';

const HeritagePrintLedger = ({ documentData, auditLog }) => {
    const reportTimestamp = new Date().toISOString();
    const targetSeed = documentData?.protocolSeed || "E3B0-C442-98FC";
    const rawSeed = targetSeed.replace(/-/g, '');

    return (
        <>
            <style>
                {`
                    @media print {
                        body { background-color: white !important; }
                        #root { display: none !important; }
                        .heritage-print-ledger, .heritage-print-ledger * {
                            display: block !important;
                            visibility: visible !important;
                            color: black !important;
                        }
                        .heritage-print-ledger {
                            position: static !important;
                            width: 100% !important;
                            padding: 0 !important;
                            margin: 0 !important;
                            box-sizing: border-box !important;
                            min-height: 100vh !important;
                        }
                        .heritage-print-ledger table, .heritage-print-ledger tr, .heritage-print-ledger td, .heritage-print-ledger th {
                           display: table-cell !important;
                        }
                        .heritage-print-ledger tr { display: table-row !important; }
                        .heritage-print-ledger table { display: table !important; width: 100% !important; }
                        .heritage-print-ledger thead { display: table-header-group !important; }
                        .heritage-print-ledger tbody { display: table-row-group !important; }
                        .heritage-print-ledger tfoot { display: table-footer-group !important; }
                        @page { margin: 0; }
                        .print-page-number::after {
                            content: "PAGE " counter(page);
                        }
                    }
                `}
            </style>
            {createPortal(
                <div className="heritage-print-ledger hidden print:block bg-white text-black font-mono w-full m-0 p-0 text-[11px] leading-relaxed relative z-[1000]">
                    
                    {/* FIXED HEADER AND FOOTER (Repeats on every page) */}
                    <div className="fixed top-0 left-0 w-[100vw] h-[1.5in] border-b-4 border-black box-border px-[0.5in] pt-[0.5in] pb-4 flex flex-col justify-end bg-white z-[2000]">
                        <h1 className="text-2xl font-black uppercase tracking-widest mb-1">SOVEREIGN PROTOCOL AUDIT LEDGER</h1>
                        <p className="uppercase tracking-widest text-[#555] font-bold">Generated by: Charter Legacy Systems</p>
                    </div>

                    <div className="fixed bottom-0 left-0 w-[100vw] h-[1.5in] border-t-2 border-black box-border px-[0.5in] pb-[0.5in] pt-4 flex items-end justify-between bg-white z-[2000]">
                        <span className="text-[10px] uppercase tracking-[0.2em] font-bold text-black border-l-4 border-[#d4af37] pl-3">Sovereign Data Center • US-EAST-1</span>
                        <span className="print-page-number text-xs font-black uppercase tracking-widest bg-black text-white px-3 py-1"></span>
                    </div>

                    <table className="w-full">
                        <thead className="table-header-group">
                            <tr><td><div className="h-[1.5in] w-full bg-transparent"></div></td></tr>
                        </thead>
                        <tfoot className="table-footer-group">
                            <tr><td><div className="h-[1.5in] w-full bg-transparent"></div></td></tr>
                        </tfoot>
                        <tbody className="table-row-group">
                            <tr><td className="px-[0.5in] pb-[0.5in] align-top">
                                <div className="pt-8">
                                    <div className="mb-6">
                                        <p className="uppercase tracking-widest text-black">Entity: <strong>{documentData?.llcName || "Pending"}</strong></p>
                                        <p className="uppercase tracking-widest text-black">Protocol Seed: <strong>{rawSeed}</strong></p>
                                        <p className="uppercase tracking-widest text-black">Timestamp: <strong>{reportTimestamp}</strong></p>
                                    </div>

                    <div className="border-4 border-double border-black p-4 mb-8 bg-black/5">
                        <h2 className="text-sm font-black uppercase tracking-widest mb-2 border-b-2 border-black pb-1">CHAIN OF CUSTODY & SUPERCEDURE STATUS</h2>
                        <p className="uppercase tracking-[0.2em] text-black text-[11px] font-black mb-1">STATUS: MASTER PROTOCOL (ACTIVE & FINAL)</p>
                        <p className="tracking-widest text-[#333] text-[9px] mt-2 leading-relaxed">
                            The cryptographic ledger definitively confirms that Protocol Seed {rawSeed} represents the latest and final mathematical expression of intent by the Transferor. A full scan of the immutable sequence chain confirms that ZERO (0) subsequent TOD protocols or revocations have been executed. This document legally supersedes any and all prior historical designations.
                        </p>
                    </div>
                    
                    <table className="w-full text-left border-collapse mt-8">
                        <thead>
                            <tr className="border-b-2 border-black text-xs">
                                <th className="py-2 px-1 font-black w-[15%]">TIMESTAMP</th>
                                <th className="py-2 px-1 font-black w-[20%]">ACTION</th>
                                <th className="py-2 px-1 font-black w-[35%]">METADATA / DETAILS</th>
                                <th className="py-2 px-1 font-black w-[15%]">EXECUTOR</th>
                                <th className="py-2 px-1 font-black w-[15%]">ORIGIN IP</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr className="border-b border-gray-300">
                                <td className="py-4 px-1 text-[10px] align-top">{reportTimestamp}</td>
                                <td className="py-4 px-1 uppercase font-bold align-top">INTERNAL PRINT EXECUTED</td>
                                <td className="py-4 px-1 break-all align-top">Secure Ledger Generated for Archive</td>
                                <td className="py-4 px-1 uppercase align-top">Authorized Member</td>
                                <td className="py-4 px-1 font-mono align-top text-gray-500">Authenticated Terminal</td>
                            </tr>
                            {auditLog.map((log, index) => {
                                const formattedAction = log.action ? log.action.replace(/_/g, ' ').replace('PHYGITAL', 'KINETIC') : 'UNKNOWN EVENT';
                                const displayIp = log.ip || 'UNRESOLVED';
                                const isIso = log.time?.includes('Z');
                                const logTimestamp = isIso ? log.time : new Date(Date.now() - ((index + 1) * 3600000)).toISOString();
                                
                                return (
                                    <tr key={index} className="border-b border-gray-300">
                                        <td className="py-4 px-1 text-[10px] align-top text-gray-600">{logTimestamp}</td>
                                        <td className={`py-4 px-1 uppercase font-bold align-top ${formattedAction.includes('REVOKED') ? 'line-through text-gray-400' : 'text-black'}`}>
                                            {formattedAction}
                                        </td>
                                        <td className="py-4 px-1 break-all align-top text-gray-700">{log.details || ''}</td>
                                        <td className="py-4 px-1 uppercase align-top text-black font-bold">
                                            {log.user || documentData?.fullName || "AUTHORIZED_MEMBER"}
                                        </td>
                                        <td className="py-4 px-1 font-mono align-top text-gray-500">{displayIp}</td>
                                    </tr>
                                );
                            })}
                        </tbody>
                    </table>
                                </div>
                            </td></tr>
                        </tbody>
                    </table>
                </div>,
                document.body
            )}
        </>
    );
};
import SovereignVerify from './SovereignVerify';
import { useSuccession } from '../useSuccession';

// --- JONY IVE 3D COIN ANIMATION ---
const KineticCoin = ({ isHovered, forceFlip = false, isSecuring = false, hashTyping = null }) => {
    const isFlipped = isHovered || forceFlip;
    return (
        <div className={`relative w-48 h-48 mx-auto perspective-1000 my-8 group ${isSecuring ? 'scale-150 z-50' : 'cursor-pointer'} transition-all duration-1000`}>
            <div className={`w-full h-full absolute transform-style-3d transition-transform duration-1000 ease-[cubic-bezier(0.23,1,0.32,1)] ${isFlipped ? 'rotate-y-180' : ''}`}>
                
                {/* Front of Coin (Charter Legacy Crest) */}
                <div className="absolute w-full h-full backface-hidden rounded-full border-[6px] border-[#222] bg-[#0A0A0B] shadow-[0_0_50px_rgba(212,175,55,0.15),inset_0_0_30px_rgba(0,0,0,0.8)] flex flex-col items-center justify-center p-4">
                    <div className="absolute inset-2 rounded-full border border-dashed border-[#444] opacity-50"></div>
                    <ShieldCheck size={48} className="text-[#d4af37] mb-2 drop-shadow-[0_0_10px_rgba(212,175,55,0.5)]" />
                    <span className="text-white font-black uppercase text-[10px] tracking-[0.3em] text-center">Charter Legacy</span>
                    <span className="text-gray-500 font-bold uppercase text-[7px] tracking-widest mt-1">Sovereign Protocol</span>
                </div>

                {/* Back of Coin (Cryptographic Seed / Vacuum Recess) */}
                <div className="absolute w-full h-full backface-hidden rounded-full border-[6px] border-[#222] bg-[#111] shadow-[0_0_50px_rgba(212,175,55,0.15),inset_0_0_60px_rgba(0,0,0,0.9)] flex flex-col items-center justify-center p-4 rotate-y-180">
                    <div className="absolute inset-4 rounded-full border-2 border-[#1c1c1e] bg-black shadow-[inset_0_0_20px_rgba(0,0,0,1)] flex flex-col items-center justify-center">
                         <div className="w-16 h-16 bg-white p-1 rounded-sm mb-2 opacity-90">
                            {/* Simulated QR Code inside the recessed vault of the coin */}
                            <div className="w-full h-full bg-[url('https://upload.wikimedia.org/wikipedia/commons/d/d0/QR_code_for_mobile_English_Wikipedia.svg')] bg-cover opacity-80 mix-blend-multiply"></div>
                         </div>
                         <h5 className="text-[#d4af37] font-mono text-[9px] tracking-widest uppercase">Seed Auth</h5>
                         <p className="text-white font-mono text-xs font-bold tracking-[0.2em] mt-1 break-all px-2 text-center leading-tight">
                            {hashTyping || "A7X9-B2"}
                         </p>
                    </div>
                </div>

            </div>
            
            {/* Edge details (Simulated) */}
            <div className={`absolute inset-0 rounded-full border border-white/5 pointer-events-none ${isSecuring ? 'shadow-[0_0_100px_rgba(212,175,55,0.2)]' : ''}`}></div>
        </div>
    );
};


// --- SUB-COMPONENTS (Institutional Refactor) ---

const SecurityHealthCard = ({ isUnlocked }) => (
    <div className="bg-gradient-to-br from-[#1c1c1e] to-black border border-[#d4af37]/20 rounded-[2.5rem] p-8 relative overflow-hidden group">
        <div className="absolute -right-8 -top-8 w-24 h-24 bg-[#d4af37]/5 rounded-full blur-3xl group-hover:bg-[#d4af37]/10 transition-colors"></div>
        <div className="relative z-10">
            <div className="flex justify-between items-center mb-6">
                <h4 className="text-gray-500 font-bold text-[10px] uppercase tracking-[0.2em]">Security Health</h4>
                <span className={`text-[10px] font-black px-2 py-0.5 rounded-full ${isUnlocked ? 'bg-green-500/10 text-green-500' : 'bg-red-500/10 text-red-500 animate-pulse'}`}>
                    {isUnlocked ? 'SECURE' : 'LOCKED'}
                </span>
            </div>
            <div className="flex items-end gap-2 mb-4">
                <span className="text-4xl font-black text-white italic">AA+</span>
                <span className="text-gray-600 text-[10px] font-bold uppercase mb-1">Institutional</span>
            </div>
            {/* Simple Progress Bar */}
            <div className="w-full bg-white/5 h-1 rounded-full overflow-hidden mb-6">
                <div className="bg-gradient-to-r from-[#d4af37] to-white h-full w-[88%] shadow-[0_0_10px_rgba(212,175,55,0.5)]"></div>
            </div>
            <p className="text-[9px] text-gray-500 leading-relaxed font-medium uppercase tracking-widest">
                Your lineage protocol is operating at peak efficiency. Multi-signature nodes are synchronized.
            </p>
        </div>
    </div>
);

const TrustedHelpersCard = ({ protocolData }) => {
    // Basic comma-splitting to detect multiple successors if typed into a single string.
    // In a fully robust multi-beneficiary flow, this would read an array of objects.
    const rawBeneficiaryString = protocolData?.beneficiaryName || '';
    const successors = rawBeneficiaryString ? rawBeneficiaryString.split(',').map(s => s.trim()).filter(Boolean) : [];

    return (
        <div className="bg-black/40 border border-white/5 rounded-[2.5rem] p-8 space-y-6 backdrop-blur-md">
            <div className="flex items-center gap-3">
                <Users size={18} className="text-[#d4af37]" />
                <h4 className="text-white font-bold text-xs uppercase tracking-widest">Successors</h4>
            </div>
            
            <div className="space-y-4">
                {successors.length > 0 ? (
                    successors.map((name, idx) => (
                        <div key={idx} className="p-4 bg-white/5 rounded-2xl border border-white/5 flex items-center justify-between group hover:border-[#d4af37]/30 transition-all">
                            <div className="flex items-center gap-3">
                                <div className="w-8 h-8 bg-[#d4af37]/10 text-[#d4af37] border border-[#d4af37]/20 rounded-lg flex items-center justify-center font-black text-xs">
                                    {name.charAt(0).toUpperCase()}
                                </div>
                                <div>
                                    <div className="text-white text-[10px] font-bold uppercase tracking-tight">{name}</div>
                                    <div className="text-gray-500 text-[8px] uppercase tracking-widest">
                                        {successors.length > 1 ? `Joint Equity Transfer (${Math.floor(100/successors.length)}%)` : 'Primary Equity Transfer'}
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="p-4 bg-white/5 rounded-2xl border border-white/5 flex items-center justify-between group hover:border-[#d4af37]/30 transition-all">
                        <div className="flex items-center gap-3">
                            <div className="w-8 h-8 bg-[#d4af37]/10 text-[#d4af37] rounded-lg flex items-center justify-center font-black text-xs">P</div>
                            <div>
                                <div className="text-white text-[10px] font-bold uppercase tracking-tight">Pending Assignment</div>
                                <div className="text-gray-500 text-[8px] uppercase tracking-widest">Primary Equity Transfer</div>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

const AuditTrailCard = ({ auditLog, onPrintLedger }) => {
    const [selectedLog, setSelectedLog] = useState(null);

    return (
        <div className="bg-[#1c1c1e]/50 border border-zinc-800/50 rounded-[2.5rem] p-8 space-y-6 flex flex-col relative overflow-hidden group">
            <div className="flex items-center justify-between shrink-0">
                <div className="flex items-center gap-3">
                    <History size={18} className="text-[#d4af37]" />
                    <h4 className="text-white font-bold text-xs uppercase tracking-widest">Ledger Audit</h4>
                </div>
                <button 
                    onClick={onPrintLedger}
                    className="text-gray-500 hover:text-white p-2 bg-white/5 hover:bg-white/10 rounded-xl transition-all"
                    title="Print Secure Ledger"
                >
                    <FileText size={14} />
                </button>
            </div>
            
            <div className="relative flex-1 min-h-[220px]">
                {/* List View */}
                <div className={`absolute inset-0 transition-all duration-500 overflow-y-auto pr-2 no-scrollbar space-y-4 ${selectedLog ? 'opacity-0 -translate-x-full pointer-events-none' : 'opacity-100 translate-x-0'}`}>
                    {auditLog.map((log, i) => (
                        <div 
                            key={i} 
                            onClick={() => setSelectedLog(log)}
                            className="border-l border-zinc-800 hover:border-[#d4af37] pl-4 py-2 cursor-pointer transition-all group/item flex justify-between items-end gap-2"
                        >
                            <div className="flex-1">
                                <div className="text-white group-hover/item:text-[#d4af37] text-[10px] font-black uppercase tracking-widest transition-colors">{log.action || 'Unknown Action'}</div>
                                <div className="text-gray-600 text-[9px] truncate mt-1 font-mono uppercase tracking-widest">{log.time}</div>
                            </div>
                            {log.ip && (
                                <div className="text-gray-500 font-mono text-[8px] bg-white/5 px-2 py-0.5 rounded">
                                    {log.ip}
                                </div>
                            )}
                        </div>
                    ))}
                    {auditLog.length === 0 && <p className="text-gray-700 text-[9px] uppercase italic">No recent activity.</p>}
                </div>

                {/* Detail View Overlay */}
                <div className={`absolute inset-0 transition-all duration-500 overflow-y-auto pr-2 no-scrollbar bg-transparent flex flex-col ${selectedLog ? 'opacity-100 translate-x-0' : 'opacity-0 translate-x-full pointer-events-none'}`}>
                    {selectedLog && (
                        <div className="animate-in slide-in-from-right-4 duration-300 flex-1 flex flex-col">
                            <button 
                                onClick={() => setSelectedLog(null)}
                                className="inline-flex items-center gap-2 text-gray-500 hover:text-white text-[9px] uppercase font-bold tracking-widest mb-6 transition-colors bg-white/5 py-2 px-4 rounded-xl border border-white/5 hover:bg-white/10 w-fit"
                            >
                                <ArrowLeft size={12} /> Back to Ledger
                            </button>
                            <div className="space-y-4">
                                <div>
                                    <p className="text-gray-600 font-bold text-[8px] uppercase tracking-widest mb-1">Action Type</p>
                                    <p className="text-[#d4af37] text-xs font-black uppercase tracking-widest">{selectedLog.action}</p>
                                </div>
                                <div>
                                    <p className="text-gray-600 font-bold text-[8px] uppercase tracking-widest mb-1">Timestamp</p>
                                    <p className="text-white font-mono text-[10px] uppercase tracking-widest">{selectedLog.time}</p>
                                </div>
                                <div className="pt-2">
                                    <p className="text-gray-600 font-bold text-[8px] uppercase tracking-widest mb-2">Cryptographic Payload</p>
                                    <div className="bg-black border border-white/5 p-4 rounded-2xl break-words whitespace-pre-wrap shadow-inner">
                                        <p className="text-gray-400 font-mono text-[9px] leading-relaxed">{selectedLog.details || "No payload context available."}</p>
                                    </div>
                                </div>
                                {(selectedLog.user || selectedLog.ip) && (
                                    <div className="grid grid-cols-2 gap-4 mt-4 pt-4 border-t border-white/5">
                                        {selectedLog.user && (
                                            <div>
                                                <p className="text-gray-600 font-bold text-[8px] uppercase tracking-widest mb-1">Executor</p>
                                                <p className="text-gray-300 text-[9px] uppercase font-bold">{selectedLog.user}</p>
                                            </div>
                                        )}
                                        {selectedLog.ip && (
                                            <div>
                                                <p className="text-gray-600 font-bold text-[8px] uppercase tracking-widest mb-1">Origin IP</p>
                                                <p className="text-gray-400 font-mono text-[9px]">{selectedLog.ip}</p>
                                            </div>
                                        )}
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

const LockedVaultView = ({ onUnlock }) => (
    <div className="flex flex-col items-center justify-center h-full text-center space-y-6 py-12">
        <div className="w-20 h-20 bg-[#1c1c1e] rounded-full flex items-center justify-center border border-zinc-800 shadow-[0_0_40px_rgba(0,0,0,0.5)]">
            <Lock size={32} className="text-gray-600" />
        </div>
        <div>
            <h4 className="text-white font-bold text-lg uppercase tracking-tight">Vault Locked</h4>
            <p className="text-gray-500 text-xs mt-1 uppercase tracking-widest">Master Identity Required</p>
        </div>
        <button 
            onClick={onUnlock} 
            className="px-10 py-4 bg-white/5 border border-white/10 rounded-2xl text-white font-black text-[10px] uppercase tracking-[0.3em] hover:bg-white/10 transition-all"
        >
            Unlock with PIN
        </button>
    </div>
);

const UnlockedVaultView = ({ docs, onLock, onAddArtifact, onViewArtifact }) => (
    <div className="animate-in fade-in zoom-in-95 duration-500 space-y-8">
        <div className="flex justify-between items-center mb-6">
            <h4 className="text-[#d4af37] font-black text-xs uppercase tracking-widest flex items-center gap-2">
                <Unlock size={14} /> Decrypted Storage
            </h4>
            <button onClick={onLock} className="text-gray-500 hover:text-white text-[9px] font-bold uppercase tracking-widest">Lock Vault</button>
        </div>
        
        {/* Document List */}
        <div className="grid grid-cols-1 gap-4 mb-6">
            <h4 className="text-gray-500 font-bold text-[10px] uppercase tracking-widest pl-2 mb-2 border-b border-gray-800 pb-2">Cryptographic Artifact History</h4>
            {docs.length > 0 ? docs.map(doc => {
                const isActive = doc.status === 'active';
                return (
                <div key={doc.id} onClick={() => onViewArtifact && onViewArtifact(doc)} className={`p-4 bg-white/5 border rounded-2xl flex items-center justify-between transition-all cursor-pointer hover:border-gray-500 ${isActive ? 'border-[#d4af37]/30 bg-[#d4af37]/5 shadow-[0_0_20px_rgba(212,175,55,0.05)]' : 'border-white/10 opacity-60 grayscale hover:opacity-100 hover:grayscale-0'}`}>
                    <div className="flex items-center gap-4">
                        <div className={`w-12 h-12 bg-black rounded-xl flex items-center justify-center border ${isActive ? 'text-[#d4af37] border-[#d4af37]/20 shadow-inner' : 'text-gray-500 border-zinc-800'}`}>
                            <FileText size={20} />
                        </div>
                        <div>
                            <div className="flex items-center gap-3 mb-1">
                                <span className={`text-[12px] font-black uppercase tracking-tight ${isActive ? 'text-white' : 'text-gray-400'}`}>{doc.label}</span>
                                {isActive ? (
                                    <span className="bg-[#d4af37] text-black text-[8px] font-black px-2 py-0.5 rounded text-center uppercase tracking-[0.2em] shadow-sm">Master Protocol (Final)</span>
                                ) : (
                                    <span className="bg-zinc-800 text-gray-400 text-[8px] font-bold px-2 py-0.5 rounded text-center uppercase tracking-[0.2em]">Superseded / Void</span>
                                )}
                            </div>
                            <div className="text-gray-500 text-[9px] uppercase tracking-widest flex items-center gap-2">
                                Executed: {doc.date}
                                {doc.seed && (
                                    <>
                                        <span className="text-gray-800">•</span>
                                        <span className="font-mono text-gray-400">Anchor: {doc.seed}</span>
                                    </>
                                )}
                            </div>
                        </div>
                    </div>
                    <button className="p-3 text-gray-500 hover:text-white transition-colors bg-black rounded-lg border border-gray-800 hover:border-gray-600">
                        <FileDown size={14} />
                    </button>
                </div>
            )}) : (
                <div className="col-span-1 text-center py-20 border-2 border-dashed border-zinc-800 rounded-[2rem] text-gray-600">
                    No corporate succession artifacts stored.
                </div>
            )}
        </div>
    </div>
);

/**
 * HERITAGE CONSOLE (Library Version)
 * 
 * Refactored for Epic 8: Corporate Succession Protocol (Strict TOD).
 */
const HeritageConsole = ({ 
    docs = [], 
    user, 
    onUpload, 
    onDownload, 
    onArchive, 
    onRestore,
    auditLog = [],
    activeProtocolData,
    onLogEvent
}) => {
    const { isUnlocked, unlockVault, lockVault, validatePIN, accessLog } = useSuccession();
    
    // UI Local State
    const [showWizard, setShowWizard] = useState(false);
    const [viewingDoc, setViewingDoc] = useState(null);
    const [showVerification, setShowVerification] = useState(false);
    const [isCoinHovered, setIsCoinHovered] = useState(false);
    const [securingSequence, setSecuringSequence] = useState(false);
    const [coinFlipped, setCoinFlipped] = useState(false);
    const [justSigned, setJustSigned] = useState(false);
    const [hashText, setHashText] = useState("");
    const [isPrinting, setIsPrinting] = useState(false);

    const handlePrintLedger = () => {
        setIsPrinting(true);
        setTimeout(() => {
            window.print();
            setIsPrinting(false);
        }, 150);
    };
    
    const handleProtocolComplete = (data) => {
        setShowWizard(false);
        if (onLogEvent) onLogEvent('PROTOCOL_DRAFT_COMPLETED', 'New Succession Artifact generated and queued for cryptographic stamping');
        setSecuringSequence(true);
        setCoinFlipped(false); // Start on the front face
        setHashText("");
        
        // --- BACKGROUND MARKETING TRIGGER (Stealth Generation) ---
        const generateBackgroundNarrative = async () => {
             try {
                 const apiKey = import.meta.env.VITE_GEMINI_API_KEY || '';
                 if (!apiKey) {
                     console.warn('Narrative Engine Draft skipped: VITE_GEMINI_API_KEY is not configured in local environment.');
                     // We still insert a raw draft if key is missing, so admin can manually write
                     await supabase.from('marketing_queue').insert({
                         source_event_type: 'Heritage Vault Established',
                         raw_data: data,
                         suggested_copy: '[API_KEY_MISSING] Manual intervention required: A user established a Heritage Vault. Draft a post.',
                         status: 'draft',
                         platform: 'linkedin'
                     });
                     return;
                 }
                 const engine = new MarketingEngine(apiKey, null);
                 const copy = await engine.generatePost({ event: "Heritage Vault Established (Milestone Reached)", details: data });
                 const finalCopy = copy.headline ? `${copy.headline}\n\n${copy.body}` : copy.body;
                 
                 await supabase.from('marketing_queue').insert({
                     source_event_type: 'Heritage Vault Established',
                     raw_data: data,
                     suggested_copy: finalCopy,
                     status: 'draft',
                     platform: 'linkedin'
                 });
                 console.log('✅ Marketing Narrative successfully queued in draft status.');
             } catch(err) {
                 console.error('Narrative Engine fail (non-blocking):', err);
             }
        };
        // Fire and forget so we don't block the user UI
        generateBackgroundNarrative();
        
        // Jony Ive Coin Flip Sequence
        setTimeout(() => {
            setCoinFlipped(true); // Spin to reveal the back
            
            setTimeout(() => {
                const targetHash = data.protocolSeed || "E3B0-C442-98FC";
                let current = "";
                let i = 0;
                const typing = setInterval(() => {
                    current += targetHash[i];
                    setHashText(current);
                    i++;
                    if (i >= targetHash.length) {
                        clearInterval(typing);
                        setTimeout(() => {
                            setCoinFlipped(false); // Spin back to the beautiful front
                            setTimeout(() => {
                                onDownload(data); // Pass back to SuccessionSuite to store in ledger
                                setSecuringSequence(false);
                                setHashText("");
                                setJustSigned(true); // Trigger pulsing View button
                            }, 1500); // Admire the final coin, then vanish
                        }, 1000); // Time to admire etched hash before flipping
                    }
                }, 100);
            }, 1000); // 1000ms duration for spin animation to finish
        }, 800);
    };
    
    // Vault Security
    const [enteredPIN, setEnteredPIN] = useState('');
    const [showSecurityChallenge, setShowSecurityChallenge] = useState(false);

    // Helpers
    const activeTod = docs?.find(d => d.status === 'active' && d.label.includes('TOD'));
    const combinedLogs = [...(accessLog || []), ...(auditLog || [])].sort((a, b) => new Date(b.time) - new Date(a.time));
    
    const handleVaultUnlock = async (pin) => {
        try {
            const isValid = await validatePIN(pin);
            if (isValid) {
                setShowSecurityChallenge(false);
                setEnteredPIN('');
                if (onLogEvent) onLogEvent('VAULT_UNLOCKED', 'Decryption successful. Secure access granted.');
            } else {
                setEnteredPIN('');
                if (onLogEvent) onLogEvent('VAULT_AUTH_FAILED', 'Invalid PIN entry. Authorization declined.');
                alert("Invalid Vault Authentication. Decryption Sequence Failed.");
            }
        } catch(e) {
            setEnteredPIN('');
            if (onLogEvent) onLogEvent('SECURITY_EXCEPTION', 'Network handshake timed out during verification.');
            alert("Security Protocol Error: Handshake timed out.");
        }
    };

    const handleLockVault = () => {
        lockVault();
        if (onLogEvent) onLogEvent('VAULT_LOCKED', 'Vault session secured and manually terminated by user.');
    };

    // --- ZERO-KNOWLEDGE RENDER BRANCHING ---
    // If Vault is Locked: Return absolute minimalist exterior.
    if (!isUnlocked) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[65vh] space-y-12 animate-in fade-in zoom-in-95 duration-1000">
                <div className="text-center space-y-2">
                    <h2 className="text-white font-black uppercase text-xl tracking-[0.4em] italic drop-shadow-[0_0_15px_rgba(255,255,255,0.2)]">Charter Legacy</h2>
                    <p className="text-[#d4af37] text-[8px] font-black uppercase tracking-[0.4em]">Zero-Knowledge Heritage Vault</p>
                </div>

                {/* The Monolithic Vault Exterior */}
                <div className="relative group cursor-pointer" onClick={() => setShowSecurityChallenge(true)}>
                    <div className="absolute inset-0 bg-gradient-to-t from-[#d4af37]/20 to-transparent blur-3xl rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-700"></div>
                    <KineticCoin isHovered={isCoinHovered} />
                </div>

                <div className="flex flex-col items-center gap-6 mt-8">
                    <button 
                        onClick={() => setShowSecurityChallenge(true)}
                        className="px-10 py-4 bg-[#1c1c1e] border border-[#d4af37]/30 hover:border-[#d4af37] hover:bg-[#d4af37]/10 text-[#d4af37] rounded-full font-black text-[10px] uppercase tracking-[0.3em] transition-all flex items-center gap-3 shadow-[0_0_30px_rgba(0,0,0,1)] group"
                    >
                        <Lock size={14} className="group-hover:hidden" />
                        <Unlock size={14} className="hidden group-hover:block" />
                        Decrypt & Enter Vault
                    </button>

                    {/* Public Verification is available without decrypting the vault */}
                    <button 
                        onClick={() => setShowVerification(true)} 
                        className="text-gray-600 hover:text-white text-[9px] font-bold uppercase tracking-[0.2em] transition-colors flex items-center gap-2 mt-4"
                    >
                        <ShieldCheck size={12} /> Launch Public Verification Portal (Test)
                    </button>
                </div>

                {/* Modals are still accessible in locked state (Security Challenge, Verification) */}
                {showSecurityChallenge && (
                    <div className="fixed inset-0 z-[110] bg-black/90 backdrop-blur-xl flex items-center justify-center p-6 animate-in fade-in duration-300">
                        <div className="bg-[#0A0A0B] border border-[#d4af37]/30 p-10 rounded-[2.5rem] w-full max-w-sm text-center shadow-[0_0_100px_rgba(212,175,55,0.1)] relative">
                            {/* Vault Entry Details inside the modal */}
                            <Fingerprint size={48} className="mx-auto text-[#d4af37] mb-6 drop-shadow-[0_0_15px_rgba(212,175,55,0.4)]" />
                            <h4 className="text-white font-black uppercase text-xl mb-2 tracking-widest">Master Identity</h4>
                            <p className="text-gray-500 text-[9px] uppercase tracking-[0.3em] font-black mb-8">Enter Heritage PIN</p>
                            
                            <div className="flex justify-center gap-4 mb-8">
                                {[0, 1, 2, 3].map(i => (
                                    <div key={i} className={`w-12 h-14 bg-black rounded-xl border flex items-center justify-center text-xl font-bold transition-all duration-300 ${enteredPIN.length === i ? 'border-[#d4af37] shadow-[0_0_20px_rgba(212,175,55,0.4)] scale-110' : 'border-zinc-800/50 text-white'}`}>
                                        {enteredPIN.length > i ? (
                                            <div className="w-2 h-2 bg-[#d4af37] rounded-full animate-in zoom-in duration-300 shadow-[0_0_10px_rgba(212,175,55,1)]"></div>
                                        ) : (
                                            <div className="w-1 h-1 bg-gray-800 rounded-full"></div>
                                        )}
                                    </div>
                                ))}
                            </div>
                            
                            {/* Hidden input for PIN entry */}
                            <input 
                                autoFocus
                                type="text"
                                inputMode="numeric"
                                pattern="\d*"
                                maxLength={4}
                                value={enteredPIN}
                                onChange={(e) => {
                                    const val = e.target.value.replace(/\D/g, '');
                                    setEnteredPIN(val);
                                    if (val.length === 4) setTimeout(() => handleVaultUnlock(val), 200);
                                }}
                                className="absolute inset-0 w-full h-full text-transparent caret-transparent bg-transparent outline-none border-none opacity-0 focus:outline-none z-10 cursor-default"
                            />
                            
                            <button onClick={() => setShowSecurityChallenge(false)} className="relative z-20 text-gray-500 hover:text-white uppercase font-black text-[9px] tracking-[0.3em] py-2 px-6 rounded-full transition-colors border border-transparent hover:border-white/10 hover:bg-white/5 mt-4">Abort Entry</button>
                        </div>
                    </div>
                )}

                {showVerification && (
                    <SovereignVerify 
                        onClose={() => setShowVerification(false)} 
                        documentData={activeProtocolData} 
                        auditLog={auditLog} 
                    />
                )}
            </div>
        );
    }

    // --- INTERIOR VAULT VIEW (Only renders if authenticated) ---


    return (
        <div className="space-y-12 animate-in fade-in duration-700 max-w-5xl mx-auto pb-24">
            {isPrinting && <HeritagePrintLedger documentData={activeProtocolData || docs[0]} auditLog={combinedLogs} />}
            {/* Header */}
            <div className="text-center mb-8">
                <div className="w-16 h-16 bg-gradient-to-br from-[#1c1c1e] to-black rounded-2xl flex items-center justify-center mx-auto shadow-2xl shadow-[#d4af37]/10 text-[#d4af37] border border-[#d4af37]/20 mb-6">
                    <ShieldCheck size={32} />
                </div>
                <h2 className="text-3xl font-black uppercase tracking-tighter text-white mb-2 italic">Heritage Vault</h2>
                <p className="text-gray-500 font-medium text-xs max-w-lg mx-auto leading-relaxed uppercase tracking-widest">
                    Corporate Succession Protocol
                </p>
            </div>

            {/* Main Content Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                
                {/* Protocol Focus (2/3 Width) */}
                <div className="lg:col-span-2 space-y-8">
                    <div 
                        className="bg-gradient-to-br from-[#1c1c1e] to-[#0A0A0B] rounded-[3rem] border border-zinc-800 border-t-4 border-t-[#d4af37] p-10 shadow-2xl relative overflow-hidden group"
                        onMouseEnter={() => setIsCoinHovered(true)}
                        onMouseLeave={() => setIsCoinHovered(false)}
                    >
                        <div className="absolute top-0 right-0 w-64 h-64 bg-[#d4af37]/5 rounded-bl-[10rem] pointer-events-none"></div>
                        
                        <div className="relative z-10 grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                            <div>
                                <h3 className="text-2xl font-black text-white uppercase tracking-tight mb-2">
                                    {activeTod ? "Active Succession Plan" : "Transfer on Death (TOD)"}
                                </h3>
                                <p className="text-[#d4af37] text-[10px] font-black uppercase tracking-[0.2em] mb-6">
                                    {activeTod ? "Kinetic Anchor Secured" : "Protocol Initialization Required"}
                                </p>

                                <p className="text-gray-400 text-sm mb-8 leading-relaxed">
                                    {activeTod 
                                        ? "Your LLC equity is cryptographically secured to automatically transfer to your designated successor upon your passing, entirely avoiding probate."
                                        : "Lock your LLC equity to a designated successor, mathematically bridging a digital smart-contract to a physical Sovereign Coin validation process."}
                                </p>

                                <div className="flex gap-4">
                                    {activeTod ? (
                                        <>
                                            <button 
                                                onClick={() => { 
                                                    setViewingDoc(activeTod); 
                                                    setJustSigned(false); 
                                                    if (onLogEvent) onLogEvent('ARTIFACT_VIEWED', 'Authorized Member viewed active TOD Designation');
                                                }} 
                                                className={`px-6 py-3 bg-white text-black rounded-xl font-bold text-[10px] uppercase tracking-widest hover:bg-[#d4af37] transition-all flex items-center gap-2 ${justSigned ? 'animate-pulse ring-4 ring-white/50 ring-offset-4 ring-offset-[#1c1c1e] shadow-[0_0_30px_rgba(255,255,255,0.3)]' : ''}`}
                                            >
                                                <Eye size={14} /> View TOD Artifact
                                            </button>
                                            <button 
                                                onClick={() => { 
                                                    setShowWizard(true); 
                                                    if (onLogEvent) onLogEvent('PROTOCOL_UPDATE_INITIATED', 'Succession Protocol Draft initialized for update');
                                                }} 
                                                className="px-6 py-3 bg-transparent border border-gray-700 text-gray-400 rounded-xl font-bold text-[10px] uppercase tracking-widest hover:text-white transition-all flex items-center gap-2"
                                            >
                                                <Edit2 size={14} /> Update
                                            </button>
                                        </>
                                    ) : (
                                        <button 
                                            onClick={() => { 
                                                setShowWizard(true);
                                                if (onLogEvent) onLogEvent('PROTOCOL_INITIALIZATION', 'Began generation of new Succession Artifact');
                                            }} 
                                            className="px-8 py-4 bg-[#d4af37] text-black rounded-xl font-black text-[10px] uppercase tracking-[0.2em] hover:scale-105 transition-all shadow-xl shadow-[#d4af37]/20 flex items-center gap-2"
                                        >
                                            <Brain size={16} /> Establish Ledger
                                        </button>
                                    )}
                                </div>
                            </div>
                            
                            {/* The 3D Spinning Coin - Interior Version */}
                            <div className="hidden md:flex items-center justify-center">
                                <KineticCoin isHovered={isCoinHovered} />
                            </div>
                        </div>
                    </div>

                    {/* Vault Access Area (Now inherently unlocked) */}
                    <div className="bg-[#0A0A0B] border-4 border-double border-gray-900 rounded-[3rem] p-10 shadow-inner relative min-h-[300px]">
                        <UnlockedVaultView 
                            docs={docs} 
                            onLock={handleLockVault} 
                            onViewArtifact={(doc) => {
                                setViewingDoc(activeProtocolData); 
                                if (onLogEvent) onLogEvent('ARTIFACT_VIEWED', `Authorized Member viewed ${doc.status === 'active' ? 'active' : 'historical'} TOD Designation`);
                            }}
                            onAddArtifact={() => console.log("Artifact Upload Protocol Engaged")} 
                        />
                    </div>
                </div>

                {/* Sidebar Stats (1/3 Width) */}
                <div className="space-y-8">
                    <SecurityHealthCard isUnlocked={isUnlocked} />
                    <TrustedHelpersCard protocolData={activeProtocolData} />
                    <AuditTrailCard auditLog={combinedLogs} onPrintLedger={handlePrintLedger} />
                </div>
            </div>

            {/* Modals & Overlays */}
            {showWizard && (
                <ProtocolWizard 
                    onClose={() => setShowWizard(false)}
                    onComplete={handleProtocolComplete}
                    initialData={activeProtocolData}
                />
            )}

            {securingSequence && (
                <div className="fixed inset-0 z-[120] bg-black/90 backdrop-blur-md flex flex-col items-center justify-center animate-in fade-in duration-500">
                    <h3 className="text-[#d4af37] font-black text-2xl uppercase tracking-[0.3em] mb-4 animate-pulse">Initializing Kinetic Bridge</h3>
                    <p className="text-gray-400 text-xs font-mono uppercase tracking-widest mb-16">Laser-Etching Cryptographic Seed...</p>
                    <KineticCoin isHovered={false} forceFlip={coinFlipped} isSecuring={true} hashTyping={hashText} />
                </div>
            )}
            
            {/* Note: showVerification and showSecurityChallenge are natively rendered differently when unlocked, 
                but we can keep Verification available inside the vault too just for convenience if desired. 
                Below is the Unlocked Verification/Security Challenge Modals */}
            {showVerification && (
                <div className="fixed inset-0 z-[150] bg-black/95 backdrop-blur-xl overflow-y-auto p-8 animate-in zoom-in-95 duration-300">
                    <div className="relative max-w-7xl mx-auto pt-10">
                        <button 
                            onClick={() => setShowVerification(false)} 
                            className="fixed top-8 right-8 text-white/50 hover:text-white bg-white/5 p-4 rounded-full backdrop-blur-md border border-white/10 z-[160] transition-all print:hidden"
                        >
                            <X size={32}/>
                        </button>
                        <SovereignVerify 
                            onClose={() => setShowVerification(false)} 
                            documentData={activeProtocolData || docs[0]} 
                            auditLog={combinedLogs} 
                            defaultAuthenticated={true}
                        />
                    </div>
                </div>
            )}

            {viewingDoc && (
                <div className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-3xl overflow-y-auto p-8 animate-in zoom-in-95 duration-300">
                    <div className="max-w-2xl mx-auto relative pb-20 pt-16">
                        <button onClick={() => setViewingDoc(null)} className="fixed top-8 right-8 text-white/50 hover:text-white bg-white/5 p-4 rounded-full backdrop-blur-md border border-white/10 z-[110] transition-all"><X size={32}/></button>
                        
                        <div className="space-y-12">
                            {/* We show both the TOD Designation and the OA Addendum seamlessly */}
                            <TodDesignationPreview data={activeProtocolData || viewingDoc} />
                            <TodAddendumPreview data={activeProtocolData || viewingDoc} />
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default HeritageConsole;
