-- 20260304024500_insert_pending_variants_rpc.sql

-- Creates a Security Definer RPC so the AIGrowthConsole can insert new pending variants 
-- generated by the Local AI, even when the developer is bypassing the staff login (and lacks a valid JWT).

CREATE OR REPLACE FUNCTION insert_pending_hero_variants(p_payload JSONB)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_record JSONB;
BEGIN
    FOR v_record IN SELECT * FROM jsonb_array_elements(p_payload)
    LOOP
        INSERT INTO hero_variants (variant_code, headline, subheading, target_sentiment, status)
        VALUES (
            v_record->>'variant_code',
            v_record->>'headline',
            v_record->>'subheading',
            v_record->>'target_sentiment',
            'PENDING'
        );
    END LOOP;
END;
$$;
